/// Flutter icons AwesomeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AwesomeIcons
///      fonts:
///       - asset: fonts/AwesomeIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AwesomeIcons {
  AwesomeIcons._();

  static const _kFontFam = 'AwesomeIcons';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ok_circled = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ok_circled2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData help_circled = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData headphones = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData text_height = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData check_empty = const IconData(0xf096, fontFamily: _kFontFam);
  static const IconData flag_checkered = const IconData(0xf11e, fontFamily: _kFontFam);
  static const IconData help = const IconData(0xf128, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xf132, fontFamily: _kFontFam);
  static const IconData extinguisher = const IconData(0xf134, fontFamily: _kFontFam);
  static const IconData angle_circled_left = const IconData(0xf137, fontFamily: _kFontFam);
  static const IconData angle_circled_right = const IconData(0xf138, fontFamily: _kFontFam);
  static const IconData angle_circled_up = const IconData(0xf139, fontFamily: _kFontFam);
  static const IconData angle_circled_down = const IconData(0xf13a, fontFamily: _kFontFam);
  static const IconData ok_squared = const IconData(0xf14a, fontFamily: _kFontFam);
  static const IconData wheelchair = const IconData(0xf193, fontFamily: _kFontFam);
  static const IconData header = const IconData(0xf1dc, fontFamily: _kFontFam);
  static const IconData shekel = const IconData(0xf20b, fontFamily: _kFontFam);
  static const IconData heartbeat = const IconData(0xf21e, fontFamily: _kFontFam);
  static const IconData calendar_check_o = const IconData(0xf274, fontFamily: _kFontFam);
  static const IconData wheelchair_alt = const IconData(0xf29b, fontFamily: _kFontFam);
  static const IconData asl_interpreting = const IconData(0xf2a4, fontFamily: _kFontFam);
  static const IconData themeisle = const IconData(0xf2b2, fontFamily: _kFontFam);
}
